### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by psteinb** [ComputationalRadiationPhysics/halt#18]
If I understand correctly, halt/liblifft is licensed under GPLv3. As it is a header-only library, I was wondering what the implications for any client to halt/liblifft are. If I wanna use it in my library/app, does that mean I have to adapt GPLv3 as well?

**Comment by Flamefire** [comment]
ccing @bussmann @ax3l as I honestly don't know
It is still possible to change the license here before other collaborators add their work.

**Comment by bussmann** [comment]
HALT ist LGPLv3 lizensiert. Damit sehe ich kein Problem. Oder hatten wir auch GPLv3 lizensiert?

**Comment by ax3l** [comment]
> If I wanna use it in my library/app, does that mean I have to adapt GPLv3 as well?

As written in most header files of it, the library `halt`/`liblifft` is licensed [**Lesser GPLv3**](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License) (more below).

So the question should read: `If I wanna use it in my library/app, does that mean I have to adapt LGPLv3 as well?`

The answer is **no** as long as you are not modifying the code we ship you as with any other LGPL library (still ship a copy of the LGPL license alongside, etc.).

Regarding the usage of our header-only library with the LGPL, we interpret and grant the same usage rights as the people at [Eigen](http://eigen.tuxfamily.org) did it for years (see [this FAQ](http://eigen.tuxfamily.org/index.php?title=Licensing_FAQ&oldid=1117)).

~~

@Flamefire After a quick check, it is not very well documented.

Please do
- add a section in the README stating the license (LGPLv3+)
- add a [COPYING.LESSER](https://github.com/ComputationalRadiationPhysics/libSplash/blob/master/COPYING.LESSER) file alongside the root path

**Comment by psteinb** [comment]
thanks for the detailed clarification. I basically took the COPYING file as *the* reference to the license that this package uses. I'll close this ticket as I feel my question is answered.

**Comment by Flamefire** [comment]
Reopening for fixing the mentioned issues
